"""empty message

Revision ID: 11e4e5f33de2
Revises: d38917a4d941
Create Date: 2023-06-05 13:34:30.862801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e4e5f33de2'
down_revision = 'd38917a4d941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_description', sa.String(length=450), nullable=True))
        batch_op.create_index(batch_op.f('ix_products_product_description'), ['product_description'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_product_image_name'), ['product_image_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_products_product_title'), ['product_title'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_product_title'))
        batch_op.drop_index(batch_op.f('ix_products_product_image_name'))
        batch_op.drop_index(batch_op.f('ix_products_product_description'))
        batch_op.drop_column('product_description')

    # ### end Alembic commands ###
