"""empty message

Revision ID: 192858f065d2
Revises: 
Create Date: 2023-05-31 13:12:17.771489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '192858f065d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('password', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('password')
    )
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_username'), ['username'], unique=True)

    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_image_name', sa.String(length=10), nullable=True),
    sa.Column('product_title', sa.String(length=150), nullable=True),
    sa.Column('product_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('product_image_name'),
    sa.UniqueConstraint('product_title')
    )
    op.create_table('laptops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foreign_key', sa.Integer(), nullable=True),
    sa.Column('processor_specifications', sa.String(length=150), nullable=True),
    sa.Column('memory_capacity_specifications', sa.String(length=250), nullable=True),
    sa.Column('display_characteristics', sa.String(length=200), nullable=True),
    sa.Column('ram_specifications', sa.String(length=200), nullable=True),
    sa.Column('number_of_ram_slots', sa.Integer(), nullable=True),
    sa.Column('graphics_card_specifications', sa.String(length=250), nullable=True),
    sa.Column('motherboard_chip_specifications', sa.String(length=150), nullable=True),
    sa.Column('other_motherboard_specs', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['foreign_key'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('laptops')
    op.drop_table('products')
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_username'))

    op.drop_table('admin')
    # ### end Alembic commands ###
