"""empty message

Revision ID: 1e750ade1996
Revises: e37638186ce7
Create Date: 2023-06-11 14:29:20.292970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e750ade1996'
down_revision = 'e37638186ce7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mouse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wireless_or_wired', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mouse', schema=None) as batch_op:
        batch_op.drop_column('wireless_or_wired')

    # ### end Alembic commands ###
