"""empty message

Revision ID: 1f26a3002a3e
Revises: 75b8dc8e44dc
Create Date: 2023-06-11 12:15:29.880936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f26a3002a3e'
down_revision = '75b8dc8e44dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pcs', schema=None) as batch_op:
        batch_op.drop_column('producing_country')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pcs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('producing_country', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
