"""empty message

Revision ID: 3035f8a5052a
Revises: 0c9d5bc09fb8
Create Date: 2023-06-04 12:05:38.887240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3035f8a5052a'
down_revision = '0c9d5bc09fb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
