"""empty message

Revision ID: 33b5fe7fb407
Revises: da4866ed6bf5
Create Date: 2023-06-11 16:15:24.804545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33b5fe7fb407'
down_revision = 'da4866ed6bf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laptops', schema=None) as batch_op:
        batch_op.drop_column('number_of_ram_slots')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laptops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_ram_slots', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
