"""empty message

Revision ID: 37a0387df38f
Revises: 
Create Date: 2023-06-03 00:36:22.776949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37a0387df38f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=25), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_image_name', sa.String(length=10), nullable=True),
    sa.Column('product_type', sa.String(length=20), nullable=True),
    sa.Column('product_title', sa.String(length=150), nullable=True),
    sa.Column('product_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('product_image_name'),
    sa.UniqueConstraint('product_title')
    )
    op.create_table('laptops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foreign_key', sa.Integer(), nullable=True),
    sa.Column('processor_specifications', sa.String(length=150), nullable=True),
    sa.Column('memory_capacity_specifications', sa.String(length=250), nullable=True),
    sa.Column('display_characteristics', sa.String(length=200), nullable=True),
    sa.Column('ram_specifications', sa.String(length=200), nullable=True),
    sa.Column('number_of_ram_slots', sa.Integer(), nullable=True),
    sa.Column('graphics_card_specifications', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['foreign_key'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('laptops')
    op.drop_table('products')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
