"""empty message

Revision ID: 601fc78e62c6
Revises: 3035f8a5052a
Create Date: 2023-06-05 11:30:45.574933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '601fc78e62c6'
down_revision = '3035f8a5052a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_product_type'), ['product_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_product_type'))

    # ### end Alembic commands ###
