"""empty message

Revision ID: 75b8dc8e44dc
Revises: 2b9dbfc5943b
Create Date: 2023-06-10 15:03:41.119355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75b8dc8e44dc'
down_revision = '2b9dbfc5943b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('ix_orders_product_image_name')
        batch_op.create_index(batch_op.f('ix_orders_product_image_name'), ['product_image_name'], unique=False)
        batch_op.drop_index('ix_orders_product_title')
        batch_op.create_index(batch_op.f('ix_orders_product_title'), ['product_title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_product_title'))
        batch_op.create_index('ix_orders_product_title', ['product_title'], unique=False)
        batch_op.drop_index(batch_op.f('ix_orders_product_image_name'))
        batch_op.create_index('ix_orders_product_image_name', ['product_image_name'], unique=False)

    # ### end Alembic commands ###
