"""empty message

Revision ID: 99b51b09300f
Revises: 
Create Date: 2023-05-30 15:10:14.256014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99b51b09300f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_image_name', sa.String(length=10), nullable=True),
    sa.Column('product_title', sa.String(length=150), nullable=True),
    sa.Column('product_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('product_image_name'),
    sa.UniqueConstraint('product_title')
    )
    op.create_table('notebooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foreign_key', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['foreign_key'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notebooks')
    op.drop_table('products')
    # ### end Alembic commands ###
