"""empty message

Revision ID: bc126316216a
Revises: 33b5fe7fb407
Create Date: 2023-06-12 12:44:37.427075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc126316216a'
down_revision = '33b5fe7fb407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sim_card_characteristics', sa.String(length=100), nullable=True))
        batch_op.drop_column('SIM_card_characteristics')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('SIM_card_characteristics', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('sim_card_characteristics')

    # ### end Alembic commands ###
