"""empty message

Revision ID: c85d1fab5273
Revises: 
Create Date: 2023-06-05 18:45:41.103074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c85d1fab5273'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=25), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_image_name', sa.String(length=65), nullable=True),
    sa.Column('product_type', sa.String(length=20), nullable=True),
    sa.Column('product_title', sa.String(length=150), nullable=True),
    sa.Column('product_description', sa.String(length=450), nullable=True),
    sa.Column('product_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_product_description'), ['product_description'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_product_image_name'), ['product_image_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_products_product_title'), ['product_title'], unique=True)
        batch_op.create_index(batch_op.f('ix_products_product_type'), ['product_type'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('laptops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foreign_key', sa.Integer(), nullable=True),
    sa.Column('processor_specifications', sa.String(length=150), nullable=True),
    sa.Column('memory_capacity_specifications', sa.String(length=250), nullable=True),
    sa.Column('display_characteristics', sa.String(length=200), nullable=True),
    sa.Column('ram_specifications', sa.String(length=200), nullable=True),
    sa.Column('number_of_ram_slots', sa.Integer(), nullable=True),
    sa.Column('graphics_card_specifications', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['foreign_key'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('laptops')
    op.drop_table('users')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_product_type'))
        batch_op.drop_index(batch_op.f('ix_products_product_title'))
        batch_op.drop_index(batch_op.f('ix_products_product_image_name'))
        batch_op.drop_index(batch_op.f('ix_products_product_description'))

    op.drop_table('products')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
