"""empty message

Revision ID: d38917a4d941
Revises: 601fc78e62c6
Create Date: 2023-06-05 11:46:29.275833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd38917a4d941'
down_revision = '601fc78e62c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('product_image_name',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=65),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('product_image_name',
               existing_type=sa.String(length=65),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
