"""empty message

Revision ID: da4866ed6bf5
Revises: ed29f5db0001
Create Date: 2023-06-11 14:35:25.558598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da4866ed6bf5'
down_revision = 'ed29f5db0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mouse', schema=None) as batch_op:
        batch_op.drop_column('wireless_or_wired')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mouse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wireless_or_wired', sa.VARCHAR(length=40), nullable=True))

    # ### end Alembic commands ###
