"""empty message

Revision ID: e37638186ce7
Revises: f75cee8a4f2b
Create Date: 2023-06-11 12:36:52.742547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e37638186ce7'
down_revision = 'f75cee8a4f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keyboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connection', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keyboard', schema=None) as batch_op:
        batch_op.drop_column('connection')

    # ### end Alembic commands ###
