"""empty message

Revision ID: ed29f5db0001
Revises: 1e750ade1996
Create Date: 2023-06-11 14:31:23.418169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed29f5db0001'
down_revision = '1e750ade1996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mouse', schema=None) as batch_op:
        batch_op.alter_column('wireless_or_wired',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=40),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mouse', schema=None) as batch_op:
        batch_op.alter_column('wireless_or_wired',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
